version: '3'
services:
  traefik:
    image: traefik:v2.10
    container_name: traefik
    ports:
      - "80:80"
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command:
      - --api.insecure=true
      - --providers.docker=true
      - "--providers.docker.exposedbydefault=false"
      - --entrypoints.web.address=:80
    labels:
      - traefik.enable=true
      - traefik.http.routers.traefik.rule=Host(`traefik.localhost`)
      - traefik.http.routers.traefik.service=api@internal
      - traefik.http.routers.traefik.entrypoints=web
  petpost:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: petpost
    restart: unless-stopped
    labels:
      - traefik.enable=true
      - traefik.http.routers.petpost.rule=Host(`petpost.localhost`)
      - traefik.http.routers.petpost.entrypoints=web
      - traefik.http.services.petpost.loadbalancer.server.port=80
