FROM nginx:alpine
WORKDIR /app
COPY app/public/. /usr/share/nginx/html/
COPY nginx/default.conf /etc/nginx/conf.d/default.conf
COPY entrypoint-prod.sh /entrypoint-prod.sh
RUN chmod +x /entrypoint-prod.sh
ENTRYPOINT ["/entrypoint-prod.sh"]
EXPOSE 80